project:
  type: website

website:
  title: "Jack's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-creating-a-blog-ChenghaoZeng

format:
  html:
    theme: "litera"
    css: ["styles.css"]





