project:
  type: website

website:
  title: "Jack's blog"
  navbar:
    left:
      - about.qmd
      - index.qmd
    right:
      - icon: facebook
        href: https://www.facebook.com/share/kZZH82qtsqw6E8qe/?mibextid=LQQJ4d
      - icon: github
        href: https://github.com/dashboard


format:
  html:
    theme: "litera"
    css: ["styles.css"]





